### ISSUE TITLE
Craft 5 support?

### ISSUE THREAD

**Issue by antcooper** [venveo/craft-compress#29]
We're just planning some site upgrades and I wonder if you're planning to support Craft 5? Thanks

**Comment by bymayo** [comment]
Any update on this?

**Comment by bymayo** [comment]
@antcooper I've just added a pull request for this, and updated it for Craft 5 (https://github.com/venveo/craft-compress/pull/30)

You can use this in your repo if you wish until Venveo accept the pull request by adding it to your composer file:

```
  "require": {
    "venveo/craft-compress": "dev-craft-5",
  }
```

And 

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/madebyshape/craft-compress.git"
    }
  ]
```

**Comment by Mosnar** [comment]
Oh awesome, thanks @bymayo!

**Comment by bymayo** [comment]
@Mosnar No problem, hopefully you merge it! :)

**Comment by Mosnar** [comment]
It's merged but I was doing some testing before tagging a release and I'm seeing some issues with the download links not working, so I'm digging into that.

**Comment by Mosnar** [comment]
I'm a dummy and forgot to set the default volume. Tagged 5.0.0!

**Comment by kennethormandy** [comment]
Thanks for this! Out of curiosity, what was the reason behind this change? https://github.com/venveo/craft-compress/commit/e3818ad44e8fa5e673eeaa52e04e396f64214857

To my knowledge, [`getContents()` is still present](https://docs.craftcms.com/api/v5/craft-elements-asset.html#method-getcontents) and unchanged in Craft 5.

It looks like that might also impact filesystems without public URLs? Maybe not though.

**Comment by bymayo** [comment]
@kennethormandy I changed this because i kept getting an error for the `getContents()` function:

```
2024-09-24 16:37:24 [web.ERROR] [Error] Error: Call to a member function getAsset() on null in /var/www/html/vendor/venveo/craft-compress/src/controllers/CompressController.php:73
```

I wasn't sure if this was because we were using Servd and their remote storage and it was struggling to grab the image.

I suppose if you want to keep the way i've done it, you could just pass the `path` rather than the `url` if some filesystems don't have public URL's

**Comment by Mosnar** [comment]
Let me look into this a little closer.

**Comment by Mosnar** [comment]
Opened #31
